#!/usr/bin/env bash

padding=20

get_bg_colour() {
  local samples=("NorthWest" "NorthEast" "SouthWest" "SouthEast")
  local red=0
  local green=0
  local blue=0
  local source="${1}"
  for sample in "${samples[@]}"; do
    local r
    local g
    local b
    IFS=" " read -r r g b <<< "$(convert "${source}" -gravity "${sample}" -crop 5x5+0+0 -format "%[fx:int(255*r+.5)] %[fx:int(255*g+.5)] %[fx:int(255*b+.5)]" info:-)"
    red="$((red+r))"
    green="$((green+g))"
    blue="$((blue+b))"
  done

  echo "rgb\($((red/4)),$((green/4)),$((blue/4))\)"
}

for source in "${@}"; do
  if [ -f "${source}" ]; then
    deskewed=$(mktemp /tmp/trim.deskewed.XXXXXX)
    magick "${source}" -background "$(get_bg_colour "${source}")" -fuzz 10% -deskew 40% +repage "${deskewed}"

    IFS=" " read -r width height x y <<< "$(magick "${deskewed}" -virtual-pixel edge -blur 0x3 -fuzz 10% -trim -format '%w %h %X %Y' info:)"
    width="$((width+padding))"
    height="$((height+0))"
    x="$((x-(padding/2)))"
    y="$((y-0))"
    dimensions="${width}x${height}+${x}+${y}"
    
    destination=$(mktemp "${source%.*}.XXXXXX.jpg")
    magick "${deskewed}" -crop "${dimensions}" +repage "${destination}"

    rm "${deskewed}"
  fi
done
