#!/usr/bin/env bash

for path in "$@"; do
  result=$(basename "${path}")
  temporary="$(mktemp -d /tmp/ocr.XXXXXX)"
  listing="${temporary%%/}/listing.txt"

  if [ "$(file "${path}" --mime-type -b)" = "application/zip" ]; then
    result="${result%.*}"
    mkdir -p "${temporary%%/}/extraction"
    unzip "${path}" -d "${temporary%%/}/extraction"
    path="${temporary%%/}/extraction"
  fi

  if [ -d "${path}" ]; then
    for file in "${path%%/}"/* ; do
      echo "${file}" >> "${listing}"
    done
  else
    result="${result%.*}"
    echo "${path}" >> "${listing}"
  fi

  destination="$(mktemp -u)"
  tesseract --dpi 300 "${listing}" "${destination}" pdf
  mv "${destination}.pdf" ./"${result}.pdf"
  rm -r "${temporary}"
done
